local _, core = ...
core.Data = {} -- adds Data table to addon namespace

local Data = core.Data

Data.spellTable = {
    "Path of the Dark Rail",
    "Path of the Iron Prow",
    "Path of the Streetwise Merchant",
    "Path of the Scrappy Prince",
    "Path of the Fallen Guardian",
    "Path of the Stout Brew",
    "Path of the Jade Serpent",
    "Path of the Bloodmaul",
    "Path of the Sire",
    "Path of the Burning Mountain",
    "Path of the Ascendant",
    "Path of the Sinful Soul",
    "Path of the Mogu King",
    "Path of the Setting Sun",
    "Path of the Scarlet Mitre",
    "Path of the Black Ox",
    "Path of the Misty Forest",
    "Path of the Stone Warden",
    "Path of the First Ones",
    "Path of the Scarlet Blade",
    "Path of the Necromancer",
    "Path of the Courageous",
    "Path of the Undefeated",
    "Path of the Tormented Soul",
    "Path of the Shado-Pan",
    "Path of the Vigilant",
    "Path of the Plagued",
    "Path of the Scheming Loa",
    "Path of the Skies",
    "Path of the Crescent Moon",
    "Path of the Verdant",
    "Teleport: Moonglade",
    "Dreamwalk",
    "Teleport: Oribos",
    "Ancient Teleport: Dalaran",
    "Teleport: Stormwind",
    "Teleport: Shattrath",
    "Teleport: Stonard",
    "Teleport: Dalaran - Northrend",
    "Teleport: Theramore",
    "Teleport: Undercity",
    "Teleport: Thunder Bluff",
    "Teleport: Exodar",
    "Teleport: Darnassus",
    "Teleport: Orgrimmar",
    "Teleport: Silvermoon",
    "Teleport: Ironforge",
    "Teleport: Shattrath",
    "Teleport: Tol Barad",
    "Teleport: Tol Barad",
    "Teleport: Orgrimmar",
    "Teleport: Hall of the Guardian",
    "Teleport: Dalaran - Broken Isles",
    "Teleport: Boralus",
    "Teleport: Hall of the Guardian",
    "Teleport: Vale of Eternal Blossoms",
    "Teleport: Dazar'alor, Teleport: Stormshield",
    "Teleport: Vale of Eternal Blossoms",
    "Teleport: Warspear",
    "Teleport: Dazar'alor",
    "Portal: Ironforge",
    "Portal: Stormwind",
    "Portal: Darnassus",
    "Portal: Exodar",
    "Portal: Theramore",
    "Portal: Vale of Eternal Blossoms",
    "Portal: Stormshield",
    "Portal: Boralus",
    "Portal: Orgrimmar",
    "Portal: Undercity",
    "Portal: Thunder Bluff",
    "Portal: Silvermoon",
    "Portal: Stonard",
    "Portal: Warspear",
    "Portal: Dazar'alor",
    "Portal: Shattrath",
    "Portal: Tol Barad",
    "Portal: Dalaran - Broken Isles",
    "Ancient Portal: Dalaran",
    "Death Gate",
    "Zen Pilgrimage",
}

Data.itemTable = {
    "Hearthstone",
    "Ancient Korthian Runes",
    "Garrison Hearthstone",
    "Dalaran Hearthstone",
    "Admiral's Compass",
    "Cloak of Coordination",
    "Wrap of Unity",
    "Wrap of Unity",
    "Shroud of Cooperation",
    "Shroud of Cooperation",
    "Argent Crusader's Tabard",
    "Admiral's Compass",
    "Flight Master's Whistle",
    "Empowered Ring of the Kirin Tor",
    "The Innkeeper's Daughter",
    "Ethereal Portal",
    "Dark Portal",
    "Ruby Slippers",
    "The Last Relic of Argus",
    "Scroll of Recall",
    "Scroll of Recall II",
    "Scroll of Recall III",
    "Astral Recall",
    "Jaina's Locket",
    "Blessed Medallion of Karabor",
    "Direbrew's Remote",
    "The Schools of Arcane Magic - Mastery",
    "Tome of Town Portal",
    "Ultrasafe Transporter: Toshley's Station",
    "Ultrasafe Transporter - Toshley's Station",
    "Ultrasafe Transporter: Gadgetzan",
    "Ultrasafe Transporter - Gadgetzan",
    "Wormhole Centrifuge",
    "Wormhole Generator: Northrend",
    "Time-Lost Artifact",
    "Stormpike Insignia Rank 1",
    "Stormpike Insignia Rank 2",
    "Stormpike Insignia Rank 3",
    "Stormpike Insignia Rank 4",
    "Stormpike Insignia Rank 5",
    "Stormpike Insignia Rank 6",
    "Beginner's Guide to Dimensional Rifting",
    "Baradin's Wardens Tabard",
    "Hellscream's Reach Tabard",
    "Pit Fighter's Punching Ring",
    "Pit Fighter's Punching Ring",
    "Pugilist's Powerful Punching Ring",
    "Pugilist's Powerful Punching Ring",
    "The Brassiest Knuckle",
    "The Brassiest Knuckle",
    "Fractured Necrolyte Skull",
    "Boots of the Bay",
}
